// vueTestTwo/trackerapp2/src/components/AddTask.vue
<template>
  <form @submit="onSubmit" class="add-form">
    <div class="form-control">
      <label>Task</label>
      <input
        v-model="text"
        type="text"
        name="text"
        placeholder="Add Task"
      />
    </div>
    <div class="form-control">
      <label>Day & Time</label>
      <input
        v-model="day"
      type="text"
      name="day"
      placeholder="Add Day & Time"
      />
    </div>
    <div class="form-control form-control-check">
      <label>Set Reminder</label>
      <input
        v-model="reminder"
      type="checkbox"
      name="reminder"
      />
    </div>

    <input type="submit" value="Save Task" class="btn btn-block" />
  </form>
</template>

<script>
  export default {
    name: 'AddTask',
    data() {
      return {
        text: '',
        day: '',
        reminder: false
      }
    },
    methods: {
      onSubmit(e) {
        e.preventDefault();

        if (!this.text) {
          alert('Please add a task');
          return
        }

        const newTask = {
          id: Math.floor(Math.random() * 100000),
          text: this.text,
          day: this.day,
          reminder: this.reminder
        }

        this.$emit('add-task', newTask)

        this.text = ''
        this.day = ''
        this.reminder = false

      }
    }
  }
</script>

<style scoped>
.add-form {
  margin-bottom: 40px;
}
.form-control {
  margin: 20px 0;
}
.form-control label {
  display: block;
}
.form-control input {
  width: 100%;
  height: 40px;
  margin: 5px;
  padding: 3px 7px;
  font-size: 17px;
}
.form-control-check {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.form-control-check label {
  flex: 1;
}
.form-control-check input {
  flex: 2;
  height: 20px;
}
</style>

// react-task-tracker/src/components/AddTask.js
import React from 'react'
import { useState } from 'react'

const AddTask = ({ onAdd }) => {

    const [name, setName] = useState('')
    const [priority, setPriority] = useState(1)
    const [reminder, setReminder] = useState(false)

    const onSubmit = (e) => {
        e.preventDefault();
        if (!name) {
            alert('Please enter a name');
            return
        }

        onAdd({name, priority, reminder });

        setName('');
        setPriority(1);
        setReminder(false);
    }

    return (
        <form className="add-form" onSubmit={onSubmit}>
            <div className="form-control">
                <label>Task:</label>
                <input type="name" placeholder="Add a New Task" value={name} onChange={(e) => setName(e.target.value)} />
            </div>
            <div className="form-control">
                <label>Priority:</label>
                <input type="Number" placeholder="1" value={priority} onChange={(e) => setPriority(e.target.value)} />
            </div>
            <div className="form-control form-control-check">
                <label>Reminder:</label>
                <input type="checkbox" checked={reminder} value={reminder} onChange={(e) => setReminder(e.currentTarget.checked)} />
            </div>           
                <input type="submit" value="Save Task" className="btn btn-block" />
        </form>
    )
}
export default AddTask
